# Generated by Django 3.1.4 on 2022-01-15 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invcategories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=100, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invgroups',
            fields=[
                ('groupid', models.IntegerField(db_column='groupID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, db_column='groupName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'invgroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invtypes',
            fields=[
                ('typeid', models.IntegerField(db_column='typeID', primary_key=True, serialize=False)),
                ('typename', models.CharField(blank=True, db_column='typeName', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('portionsize', models.IntegerField(blank=True, db_column='portionSize', null=True)),
                ('raceid', models.IntegerField(blank=True, db_column='raceID', null=True)),
                ('baseprice', models.DecimalField(blank=True, db_column='basePrice', decimal_places=4, max_digits=19, null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
                ('marketgroupid', models.IntegerField(blank=True, db_column='marketGroupID', null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('soundid', models.IntegerField(blank=True, db_column='soundID', null=True)),
                ('graphicid', models.IntegerField(blank=True, db_column='graphicID', null=True)),
            ],
            options={
                'db_table': 'invtypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('character_name', models.CharField(default='', max_length=200)),
                ('character_id', models.CharField(max_length=150, unique=True)),
                ('owner_hash', models.CharField(max_length=200)),
                ('is_updated', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.IntegerField()),
                ('te', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('copies', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invtypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='selections',
            constraint=models.UniqueConstraint(fields=('user', 'blueprint'), name='unique_selection'),
        ),
    ]
