# Generated by Django 3.1.4 on 2022-01-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invcategories',
        ),
        migrations.DeleteModel(
            name='Invgroups',
        ),
    ]
