# Generated by Django 3.1.4 on 2022-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220115_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invgroups',
            fields=[
                ('groupid', models.IntegerField(db_column='groupID', primary_key=True, serialize=False)),
                ('categoryid', models.IntegerField(blank=True, db_column='categoryID', null=True)),
                ('groupname', models.CharField(blank=True, db_column='groupName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'invgroups',
                'managed': False,
            },
        ),
    ]
