# Generated by Django 3.1.4 on 2022-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invcategories',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=100, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invcategories',
                'managed': False,
            },
        ),
    ]
